# Generated by Django 3.2.16 on 2026-01-15 03:03

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)])),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='albums/')),
                ('type', models.CharField(choices=[('ALBUM', 'Studio Album'), ('SINGLE', 'Single'), ('COMPILATION', 'Compilation'), ('EP', 'EP')], default='ALBUM', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Composition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='music/')),
                ('duration', models.DurationField(help_text='Duration in HH:MM:SS')),
                ('style', models.CharField(blank=True, max_length=100)),
                ('play_count', models.PositiveIntegerField(default=0)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='music.album')),
            ],
        ),
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='performers/')),
                ('type', models.CharField(choices=[('SOLO', 'Solo Performer'), ('GROUP', 'Group'), ('ORCHESTRA', 'Orchestra'), ('ENSEMBLE', 'Ensemble')], default='SOLO', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LIKE', 'Like'), ('DOWNLOAD', 'Download'), ('LISTEN', 'Listen'), ('FAVORITE_PERFORMER', 'Favorite Performer')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('composition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.composition')),
                ('performer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.performer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='performer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='music.performer'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['user', 'action'], name='music_useri_user_id_4e4bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='userinteraction',
            index=models.Index(fields=['composition', 'action'], name='music_useri_composi_5f609a_idx'),
        ),
    ]
